### PR TITLE
Fix date format in samples data

### LINKED ISSUE #435: Incorrect date format in some sample data files
Some sample data files have an incorrect format of "yyyy, mm, dd" which causes an error in the date picker when trying to convert the string to a Date object. The correct format of the date string should be "yyyy-mm-dd".

### PR DESCRIPTION
**Pull request by IMinchev64**
Resolves #435

### CODE REVIEW

**Review by MayaKirova — COMMENTED** [review]
Personally I'd be most for the dd/mm/yyyy format (i.e. "07/12/2023"). But I guess it doesn't matter as long as it can be parsed as a date object. Also not sure if all of the dates need changing. It seemed that the problem was just with the ones with "," (for example "2014, 5, 14"). The other ones were fine as they were.

**Comment by IMinchev64** [comment]
> Personally I'd be most for the dd/mm/yyyy format (i.e. "07/12/2023"). But I guess it doesn't matter as long as it can be parsed as a date object. Also not sure if all of the dates need changing. It seemed that the problem was just with the ones with "," (for example "2014, 5, 14"). The other ones were fine as they were.

I was left with the impression (and just doublechecked to make sure) that the format mm/dd/yyyy (and even dd/mm/yyyy) has the same problem as the one with ",". That is why I changed all of them.

**Comment by HUSSAR-mtrela** [comment]
@gmurray81 Does the CodeGen expect dates to have specific format separator? 
e.g. mm-dd-yyyy instead of mm/dd/yyyy

**Comment by gmurray81** [comment]
@HUSSAR-mtrela the code gen doesn't yet auto detect that there are dates and transform from strings to dates in the emitted code, but this is something we were considering adding. I'm guessing that @IMinchev64 and @MayaKirova are more talking about either leaving the dates as strings for grid samples, or perhaps the grid will expect specific string patterns and autodetect them as dates and convert?

The existing approach we've been using for the xplat samples for data sources that NEED the fields to be dates is to use a code based data source. For example see MultipleStocks as an example. This is really a work around though. It would be nice to be able to indicate somewhere that we'd like the dates transformed to actual dates in the emitted sample. Although, there is an argument to be made to just make all teh components auto-recognize particular date formats. And that would be another solution.

Is this what is going on here? @IMinchev64 @MayaKirova ?

**Comment by gmurray81** [comment]
Note, MultipleStocks is fetching data from json files and then converting the dates to Date type. But the relevant part to this discussion is that there is some code doing the conversion of string to date before the values hit the component.

**Comment by MayaKirova** [comment]
I think these are mostly data sources that the grid uses. In case the grid has a column that is set to have data type "date" it will try to create a new data from it (i.e. new Date("stringDateHere")) if it is not a date object. So as long as it's something that is in a valid date format it should work as expected.

**Review by HUSSAR-mtrela — APPROVED** [review]

**Pull request merged**
