### PR TITLE
Add typography class to each sample container in each template

### PR DESCRIPTION
**Pull request by mddragnev**
Add typography class to each template
Related to https://github.com/IgniteUI/igniteui-angular/issues/12942 

https://www.infragistics.com/products/ignite-ui-angular/angular/components/themes/typography

### CODE REVIEW

**Comment by HUSSAR-mtrela** [comment]
@mddragnev where is the "ig-typography" class defines and don't we need to link/import a new CSS before we can use it in samples? Also, your PR updates templates used for converting xplat samples to platform specific samples but don't you need to add "ig-typography" class to all non-xplat samples in blazor, react, angular, webcomponent samples repos?

@gmurray81 do you approve this change that introduces a new dependency on all our samples?

**Comment by mddragnev** [comment]
> @mddragnev where is the "ig-typography" class defines and don't we need to link/import a new CSS before we can use it in samples? Also, your PR updates templates used for converting xplat samples to platform specific samples but don't you need to add "ig-typography" class to all non-xplat samples in blazor, react, angular, webcomponent samples repos?
> 
> @gmurray81 do you approve this change that introduces a new dependency on all our samples?

@HUSSAR-mtrela We are not introducing new dependency. This class is defined within the grid theme that is being imported in all our samples anyway. Yes, you are correct that all custom samples for all platforms should be updated as well. The angular samples that are produced by [igniteui-angular-samples](https://github.com/IgniteUI/igniteui-angular-samples) already have it.

**Comment by HUSSAR-mtrela** [comment]
@mddragnev can you show us code where "the grid theme that is being imported in **ALL** our samples"? 

Do you mean this [import line](https://github.com/IgniteUI/igniteui-xplat-examples/blob/23.2.x/editor-templates/WebComponents/main-template/src/index.ts#L17)? If so it is used only for grids (see `ifdef` comments) and not all components. Removing those `ifdef` to import it for all components, would introduce a new dependency on the igniteui grids package!

**Comment by mddragnev** [comment]
> @mddragnev can you show us code where "the grid theme that is being imported in **ALL** our samples"?
> 
> Do you mean this [import line](https://github.com/IgniteUI/igniteui-xplat-examples/blob/23.2.x/editor-templates/WebComponents/main-template/src/index.ts#L17)? If so it is used only for grids (see `ifdef` comments) and not all components. Removing those `ifdef` to import it for all components, would introduce a new dependency on the igniteui grids package!

Yes I understand that now. The import line you sent was that i was talking about. Could we add this class to the container element only for grids maybe with conditions somehow? I dont think that this is something we have when importing the theme for the other components. Also I dont really think that it could hurt it to be there as a class and only apply styles when the grid theme is imported.

**Comment by HUSSAR-mtrela** [comment]
@gmurray81 What should we do?

1 Add "ig-typography" class to all samples but only grids samples we actually use it
2 Add "ig-typography" class AND add grids package to all samples?
3 Wrap `ifdef` around `div` with "ig-typography" class for webgrids
4 some other solution?

**Comment by HUSSAR-mtrela** [comment]
After talking to Graham, we decided to go with solution 3 (wrap `ifdef` around `div`) and I updated your PR. However, I cannot merge it right now because we are waiting for this PR to be merged first:
https://infragistics.visualstudio.com/NetAdvantage/_git/dev-tools/pullrequest/10561

**Comment by gmurray81** [comment]
btw, @HUSSAR-mtrela that was merged.

**Review by HUSSAR-mtrela — APPROVED** [review]

**Pull request merged**
