### PR TITLE
Add column resizing event handler

### PR DESCRIPTION
**Pull request by mddragnev**

### CODE REVIEW

**Review by dkamburov — APPROVED** [review]

**Comment by gmurray81** [comment]
I'm thinking that we shouldn't have needed this. The WC events should adapt to the react events generally... but maybe our transform doesn't understand how to do that with CustomEvent<T>. One problem might be that we wouldn't necessarily be able to infer the type of sender....

**Comment by dkamburov** [comment]
It would be easier to do the react handlers, not sure how much time it will take us to modify the translator replacing the args and arg types, it doesn't sound like an easy task to do.

Also not sure how these [document.getElementById](https://github.com/IgniteUI/igniteui-xplat-examples/blob/23.2.x/code-gen-library/WebGridCellEdit/Web.ts#L10) are going to be handled.

**Comment by gmurray81** [comment]
@dkamburov it may not be that bad actually.... since we have some some metadata available about the event. But also we could take a strategy similar to WPF where we rely on a bit more metadata in a comment. I'd prefer to avoid that if possible though.

**Comment by gmurray81** [comment]
I'll try to look at it later tonight.

Note, for getting a ref to the main component there is already a standard way to do this that will resolve appropriately for react/WC. If you look at how CodeGenHelper is used. This gets transformed to work differently per output platform.

The trickier one is the events where we want refs (preferably react refs to the elements created in a template) I think I can show a better way to do this. Maybe I'll have time to adjust some of them later this evening.

**Comment by gmurray81** [comment]
btw, what I'm talking about is if you write:

```ts
const grid = CodeGenHelper.getDescription<IgcGridComponent>("content");
```
where "content" matches up to the entry in the sample json descriptions.content
where the grid is described.

then when it emits to the actual sample it will be transformed to:

```ts
const grid = this.grid;
```

where it knows which field it stashed the ref to the grid in in the sample.

**Pull request merged**
