### PR TITLE
Add hgrid export excel samples

### PR DESCRIPTION
**Pull request by georgianastasov**

### CODE REVIEW

**Comment by IMinchev64** [comment]
The XPLAT samples seem to not be loading all the data for WC and React. It seems that the hGrid has some problems when loading data from a class so we might want the data to be generated as a JSON for the hGrid samples.

This can easily be achieved by adding an `XPLAT-CONFIG.json` file in the data folder as in [this commit](https://github.com/IgniteUI/igniteui-xplat-examples/pull/499/commits/528bde00d73d51aff643114d5bfe83212d35f824).

Even with this change though, the WC excel-export sample does not load the child grids in the row islands for some reason.

**Comment by georgianastasov** [comment]
Updated sample structure and added new data to align with Angular Hierarchical Grid Excel Export [sample](https://www.infragistics.com/products/ignite-ui-angular/angular/components/hierarchicalgrid/export-excel#angular-excel-exporter-example) for consistency.

**Comment by IMinchev64** [comment]
For some reason the WC samples continue to not show any data in the child grids. Can you try and figure out the reason, please? I suspect it has something to do with the WC template since I don't think there are any problems with the data structure anymore (as the other two platforms work great).

Additionally, I encountered two issues with the multi-column-headers-export samples:
- in React the `IgrExporterEventArgs` class, which is used in the `webGridExportEventMultiColumnHeaders` template, is generated as `IgrExporterEventEventArgs `
- no data file is being generated for the Blazor sample

**Comment by IMinchev64** [comment]
I figured out why the WC samples were not showing any data in the child grids. The generated samples use igniteui-webcomponents version 4.7.1, while the hierarchical grid is added in 4.8.0 or so it seems. I changed the version and the child grids were fixed.

**Comment by georgianastasov** [comment]
Yes, I actually use these versions: "@infragistics/igniteui-webcomponents-grids": "23.2.141", "@infragistics/igniteui-webcomponents-core": "23.2.141", "@infragistics/igniteui-webcomponents-layouts": "23.2.141", "@infragistics/igniteui-webcomponents-inputs": "23.2.141" and everything works as expected for me.

**Comment by georgianastasov** [comment]
After investigating the problem of data file generation in the Blazor sample, I discovered that the root cause was null values within the dataset. To rectify this, I've conducted a thorough data refactor, replacing null values with appropriate alternatives. As a result, the data now generates successfully without any issues.

**Review by IMinchev64 — APPROVED** [review]

**Pull request merged**
